config/routes.rb
Rails.application.routes.draw do

#  devise_for :users
	root to: "home#index", to: 'home#presentation'


	get '/technologie', to: 'home#index'
	# mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

	# devise_for :users

	post '/equipe', to: 'equipe#create'
	get '/equipe', to: 'equipe#index'

	resources :charges, only: [:don, :create, :thanks]

	get '/fondation', to: 'home#fondation'
	get 'presentation', to: 'home#presentation'

	get '/don', to: 'charges#donation'
	post '/don', to: 'charges#create'
	get '/donateurs', to: 'charges#donateurs'

	get '/partenaires', to: 'home#partners'

	post '/search', to: 'home#search'
	get '/search/:plante', to: 'home#search2'

	get '/profil', to: 'home#profil'
	get '/add', to: 'plantes#add'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
end

app/controllers/equipe_controller.rb
class EquipeController < ApplicationController
  def index
  end

  def create
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def search
    redirect_to "/search/#{params[:plante_search].upcase}"
  end

  def search2
    @plante_cherche = params[:plante].upcase

    if params[:plante] != nil && Plantae.find_by(Plante: @plante_cherche) != nil
      @id_plante_search = Plantae.find_by(Plante: @plante_cherche).id

      @tab_association_plante = Association.where(plantae_id2: @id_plante_search )
    else
      redirect_to root_path
    end
  end

  def presentation
  end

  def profil
    if user_signed_in?
      @id_user = current_user.id
      @tab_don = Don.where(user_id: @id_user)
    end
  end
end

app/controllers/plantes_controller.rb
class PlantesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/equipe_helper.rb
module EquipeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/plantes_helper.rb
module PlantesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/charges/create.html.erb
<div style="background-color: pink;">
	<br><br><br>
</div>
<br>

<center>
	<h1>Merci d'avoir fait don de <%= @don_float %>€ :)</h1>
</center>
<br><br>

app/views/charges/donateurs.html.erb
<div class="page-titles-img title-space-lg parallax-overlay bg-parallax" data-jarallax='{"speed": 0.4}' style='background-image: url(<%=asset_path 'dons.jpg' %>);background-position:center;'>
  <div class="container">
      <div class="row">
          <div class=" col-md-12">
              <h1 class="text-uppercase">Liste des membres donnateurs </h1>
          </div>
      </div>
  </div>
</div><!--page title end-->
<div class="container">

  <div class="row">


    <div class="row">

      <% @donateurs.each do |donation| %>

      <div class="col-lg-4 col-md-6 mb-4">
	       <div class="card h-100">
	          <%= image_tag("avatar.jpeg", size: "358x255") %>
	           <div class="card-body">
	              <h5><%= donation.user.surname.upcase + " " + donation.user.name.capitalize%></h5>
	               <p class="card-text">
                   <% if donation.user != nil %>
	                  a fait un don de <%= donation.don %>€
	                <% else %>
	                    Un Anonyme a fait un don de <%= donation.don %>€
	                <% end %></p>
	           </div>
          </div>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/charges/donation.html.erb
<div class="page-titles-img title-space-lg parallax-overlay bg-parallax" data-jarallax='{"speed": 0.4}' style='background-image: url(<%=asset_path 'dons.jpg' %>);background-position:top center;'>
  <div class="container">
      <div class="row">
          <div class=" col-md-12">
              <h1 class="text-uppercase">Don</h1>

          </div>
      </div>
  </div>
</div><!--page title end-->

<div class="container pt90 pb50">
            <p class="lead text-center">
                Phrase d'accroche qui donne envie de s'intéresser au projet.
            </p>
            <br>
            <p>
              Suo placet sumque curant hic ubi. Sua carnem hac qua mem saltem falsum. Tanta simus fas solae iii ipsum annos. Fruebatur dum naturales sui praefatio ope extitisse. Ens ubi hoc statuendum expectanti facillimum objectivus aucupantur. Disputo de mutuari is obscure me. Operae hac dicere volunt nec pileos judico dividi. Ut addo nota id fide. Ut vi igni sane vita in ulla.
            </p>
            <br>

        <div class="bg-faded pt90 pb60">
            <div class="container">
                <div class="title-heading1 mb40">
                    <h3>Pourquoi nous soutenir ?</h3>
                </div>
                <div class="row">
                    <div class="col-lg-4 mb30">
                        <div class="icon-box icon-box-center icon-border-box bg-white">
                            <i class="icon-hover-1 bg-default icon-hover-default">1</i>
                            <h4>Argument 1</h4>
                            <p>
                                Molestiae, repudiandae, maxime, earum, sapiente assumenda non odit laborum qui vero vel quos sint excepturi in laudantium.
                            </p>
                        </div>
                    </div>
                    <div class="col-lg-4 mb30">
                        <div class="icon-box icon-box-center icon-border-box bg-white">
                            <i class="icon-hover-1 bg-dark icon-hover-default">2</i>
                            <h4>Argument 2</h4>
                            <p>
                                Molestiae, repudiandae, maxime, earum, sapiente assumenda non odit laborum qui vero vel quos sint excepturi in laudantium.
                            </p>
                        </div>
                    </div>
                    <div class="col-lg-4 mb30">
                        <div class="icon-box icon-box-center icon-border-box bg-white">
                            <i class="icon-hover-1 bg-success icon-hover-default">3</i>
                            <h4>Argument 3</h4>
                            <p>
                                Molestiae, repudiandae, maxime, earum, sapiente assumenda non odit laborum qui vero vel quos sint excepturi in laudantium.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container mb50 pt90">
            <div class="title-heading1 mb40">
                <h3>Comment donner ?</h3>
            </div>
            <div class="row">
                <div class="col-md-8 mb40">

                    <p>
                        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.
                    </p>

                </div class="col-md-5 mb40">
                    <%= form_tag don_path do |f| %>

                      <article>
                        <% if flash[:error].present? %>
                          <div id="error_explanation">
                          <p><%= flash[:error] %></p>
                          </div>
                        <% end %>

                        <label class="amount">
                          <p>Montant libre :</p>
                          <input type="text" name="user_donation" id="user_donation"> €
                        </label>
                      </article>

                      <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                              data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                              data-currency="eur"
                              data-description="A month's subscription"
                              data-locale="auto">
                      </script>

                    <% end %>
                </div>

                <!-- <br><br><br><br>
                <%= form_for :user do |f| %>
                <%= f.text_field :email, placeholder: "example@gmail.com" %> <br>
                <%= f.submit "Send an email to this mail" %>
                <% end %> -->
        </div> <!-- fin container -->
        <br>
  <center>
    <h2> <a href="/donateurs">Voir tous les donateurs</a> </h2>
  </center>

app/views/equipe/create.html.erb
<h1>Equipe#create</h1>
<p>Find me in app/views/equipe/create.html.erb</p>

app/views/equipe/index.html.erb
<div class="page-titles-img title-space-lg bg-parallax parallax-overlay" data-jarallax='{"speed": 0.2}' style='background-image: url(<%= asset_path 'equipe.jpg' %>)'>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 ml-auto mr-auto">
                <h1 class='text-uppercase'>Une équipe qui s'agrandit tout les jours</h1>

             </div>
        </div>
    </div>
</div><!--page title end-->
<div class="item">
        <div class="icon-box icon-box-center">
            <i class="icon-hover-1 bg-dark fa fa-thumbs-up icon-hover-default"></i>
            <h4>Une équipe internationnale de scientifiques et chercheurs</h4>
            <p>
                Plus de 80 nationnalitées représentées
            </p>
        </div>
    </div>
    <div class="item">
        <div class="icon-box icon-box-center">
            <i class="icon-hover-1 bg-dark fa fa-mobile icon-hover-default"></i>
            <h4>Des corps de métiers différents</h4>
            <p>
              Plus de 40 filières représentées collaborant ensemble.
              </p>
        </div>
    </div>
    <div class="item">
        <div class="icon-box icon-box-center">
            <i class="icon-hover-1 bg-dark fa fa-twitter icon-hover-default"></i>
            <h4> Des sites de test</h4>
            <p>
                12 espaces de test et lieux mise à disposition du projet
            </p>
        </div>
    </div>
    <div class="item">
        <div class="icon-box icon-box-center">
            <i class="icon-hover-1 bg-dark fa fa-twitter icon-hover-default"></i>
            <h4>Des partenaires</h4>
            <p>
                Une collaboration réunissant une 100 aines d'acteurs privés
            </p>
        </div>
    </div>
    <div class="item">
        <div class="icon-box icon-box-center">
            <i class="icon-hover-1 bg-dark fa fa-twitter icon-hover-default"></i>
            <h4>Des états engagés</h4>
            <p>
              Depuis la cop 21 de nombreux états nous rejoingne
            </p>
        </div>
    </div>
    <div class="item">
        <div class="icon-box icon-box-center">
            <i class="icon-hover-1 bg-dark fa fa-code icon-hover-default"></i>
            <h4>Une grande famille</h4>
            <p>
                Plus de 200 000 donnateurs
            </p>
        </div>
    </div>
</div> <!-- /Carousel -->
</div>
<div class='container-fluid pt40 mb40'>
    <div class='row no-margin'>
        <div class='col-lg-8  mr-auto ml-auto'>
          <h2>Le mot du fondateur</h2>
            <p class='lead mb50 text-center'>
                  La nature est une resource infini dont nous cherchons à extraire la connaissance via l'étude, la recherche et le biomimétisme.</br>
                  Notre projet, notre objectif, le partage d'une connaissance <b>open-source</b> de la nature et de la vie
            </p>
        </div>
    </div>

<!--     <div class="title-heading1 mb60">
                <h3>Team - Circle</h3>
            </div> -->
	<div class="row pb60">
	    <div class="col-lg-3 col-md-6  mb30">
	        <div class="team-card-default">
	            <img src=<%= asset_path 'team1.jpg' %> alt="" class="img-fluid rounded-circle">
	            <div class="team-default-content text-center pt30">
	                    <h4 class="mb0 text-uppercase">Hadia bouria</h4>
	                    <span>Marketing manager</span>
	                    <!-- <ul class="list-inline pt10">
	                        <li class="list-inline-item">
	                            <a href="#"><i class="fa fa-facebook"></i></a>
	                        </li>
	                        <li class="list-inline-item">
	                            <a href="#"><i class="fa fa-twitter"></i></a>
	                        </li>
	                        <li class="list-inline-item">
	                            <a href="#"> <i class="fa fa-youtube"></i></a>
	                        </li>
	                        <li class="list-inline-item">
	                            <a href="#"><i class="fa fa-instagram"></i></a>
	                        </li>
	                    </ul> -->
	            </div>
	        </div>
	    </div><!--/col-->
	    <div class="col-lg-3 col-md-6  mb30">
	        <div class="team-card-default">
	            <img src=<%= asset_path 'team2.jpg' %> alt="" class="img-fluid rounded-circle">
	            <div class="team-default-content text-center pt30">
	                    <h4 class="mb0 text-uppercase">Joanne Rabenarisoa</h4>
	                    <span>Marketing manager</span>
	                    <!-- <ul class="list-inline pt10">
	                        <li class="list-inline-item">
	                            <a href="#"><i class="fa fa-facebook"></i></a>
	                        </li>
	                        <li class="list-inline-item">
	                            <a href="#"><i class="fa fa-twitter"></i></a>
	                        </li>
	                        <li class="list-inline-item">
	                            <a href="#"> <i class="fa fa-youtube"></i></a>
	                        </li>
	                        <li class="list-inline-item">
	                            <a href="#"><i class="fa fa-instagram"></i></a>
	                        </li>
	                    </ul> -->
	            </div>
	        </div>
	    </div><!--/col-->
	     <div class="col-lg-3 col-md-6  mb30">
	        <div class="team-card-default">
	            <img src=<%= asset_path 'team3.jpg' %> alt="" class="img-fluid rounded-circle">
	            <div class="team-default-content text-center pt30">
	                    <h4 class="mb0 text-uppercase">Mai lan peng</h4>
	                    <span>Marketing manager</span>
	                    <!-- <ul class="list-inline pt10">
	                        <li class="list-inline-item">
	                            <a href="#"><i class="fa fa-facebook"></i></a>
	                        </li>
	                        <li class="list-inline-item">
	                            <a href="#"><i class="fa fa-twitter"></i></a>
	                        </li>
	                        <li class="list-inline-item">
	                            <a href="#"> <i class="fa fa-youtube"></i></a>
	                        </li>
	                        <li class="list-inline-item">
	                            <a href="#"><i class="fa fa-instagram"></i></a>
	                        </li>
	                    </ul> -->
	            </div>
	        </div>
	    </div><!--/col-->
	     <div class="col-lg-3 col-md-6  mb30">
	        <div class="team-card-default">
	            <img src=<%= asset_path 'team4.jpg' %> alt="" class="img-fluid rounded-circle">
	            <div class="team-default-content text-center pt30">
	                    <h4 class="mb0 text-uppercase">Gwendoline Cassand</h4>
	                    <span>Marketing manager</span>
	                    <!-- <ul class="list-inline pt10">
	                        <li class="list-inline-item">
	                            <a href="#"><i class="fa fa-facebook"></i></a>
	                        </li>
	                        <li class="list-inline-item">
	                            <a href="#"><i class="fa fa-twitter"></i></a>
	                        </li>
	                        <li class="list-inline-item">
	                            <a href="#"> <i class="fa fa-youtube"></i></a>
	                        </li>
	                        <li class="list-inline-item">
	                            <a href="#"><i class="fa fa-instagram"></i></a>
	                        </li>
	                    </ul> -->
	            </div>
	        </div>
	    </div><!--/col-->

	</div>
</div>

<div class="container">
	<div class="title-heading1 mb60">
	    <h3>Rejoignez-nous</h3>
	</div>
    <div class="row pb30 align-items-end">
        <div class="col-lg-6 col-md-6 mb90">
        	<blockquote class="blockquote text-center">
        		<p class="mb-0">"Dans la nature, tout a toujours une raison. Si tu comprends cette raison, tu n'as plus besoin de l'expérience."</p>
        		<footer class="blockquote-footer">Léonard de Vinci</footer>
        	</blockquote>
        </div>
        <div class="col-lg-5 col-md-6 mb20">
            <form action= "/equipe" method= "post">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Nom" name= "name">
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Prénom" name= "frist_name">
                </div>
                <div class="form-group">
                    <input type="email" class="form-control" placeholder="Email" name= "email">
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Description">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-rounded btn-primary btn-block">Envoyer</button>
                </div>
            </form>
        </div>

    </div>
</div>

<!--
<div class="form-group" style="margin-left: 43%; margin-top: 2%">
	<button type="submit" class="btn btn-rounded btn-primary">Nous rejoindre</button>
</div> -->
<!--
<form action= "/equipe" method= "post"></br>
  <input type= "text" name= "name"></input></br>
  <input type= "email" name= "email"></input></br>
  <input type= "text" name= "phone_number"></input></br>
  <input name="authenticity_token" type="hidden" value="J7CBxfHalt49OSHp27hblqK20c9PgwJ108nDHX/8Cts=" />
  <button type= "submit">Postuler</button>
</form>
 -->

app/views/home/fondation.html.erb
<div class="page-titles-img title-space-lg parallax-overlay bg-parallax" data-jarallax='{"speed": 0.4}' style='background-image: url("images/bg13.jpg");background-position:top center;'>
  <div class="container">
      <div class="row">
          <div class=" col-md-12">
              <h1 class="text-uppercase">Fondation  </h1>
          </div>
      </div>
  </div>
</div><!--page title end-->

<div class = "carousel">
  <div class="container mb80">
            <div class="fancy-title mb30">
                <div class="fancy-title-sep gray-sep"></div>
            </div><!--title-->
            <!-- Carousel -->
            <div class="carousel-image owl-carousel owl-theme">
                <div class="item">
                    <img src="http://www.initiativesfleuves.org/wp-content/uploads/2018/04/foretamazonienne-1.jpg" alt="" class="img-fluid">
                </div>
                <div class="item">
                    <img src="https://i0.wp.com/mrmondialisation.org/wp-content/uploads/2017/10/WWFLUNGS.jpg" alt="" class="img-fluid">
                </div>
                <div class="item">
                    <img src="http://www.brasilpassion.com/wp-content/uploads/2013/11/foret7.jpg" alt="" class="img-fluid">
                </div>
            <div class="item">
                    <img src="http://www.brasilpassion.com/wp-content/uploads/2013/11/foret7.jpg" alt="" class="img-fluid">
                </div>
            </div> <!-- /Carousel -->
        </div>
      </div>
      <div class="container pt90  pb60">
                  <div class="row align-items-center">
                      <div class="col-lg-6 mb30">
                          <img src="https://medias.liberation.fr/photo/1102777-000_sy34r.jpg?modified_at=1520438871&width=960" alt="" class="img-fluid">
                      </div>
                      <div class="col-lg-6 mb30">
                          <h2>
                              Une bonne compréhension des écosytèmes pour une planète qui sourit
                          </h2>
                          <p>
                              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                          </p>
                          <p>
                              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                          </p>
                          <p>
                              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                          </p>
                      </div>
                  </div>
              </div>
</br></br></br></br></br>

app/views/home/partners.html.erb
<div class="page-titles-img title-space-lg parallax-overlay bg-parallax" data-jarallax='{"speed": 0.4}' style='background-image: url(<%=asset_path 'business.jpg' %>);background-position:center;'>
    <div class="container">
        <div class="row">
            <div class=" col-md-12">
                <h1 class="text-uppercase">Ils nous font confiance </h1>

            </div>
        </div>
    </div>
</div>
<div class="container pt90 pb50">
  <div class="center-title mb60 ">
  <p>Les Alliances et soutiens. Ensemble, nous travaillons a un avenir plus productif et en harmonie avec l’environnement.
Ils s’engagent a nos cotes, nous permettent de développer notre vision, nous les remercions pour leur implication.
</p>
</div>
    <div class="title-heading1 mb60">
        <h3>Mécenats</h3>
    </div>
    <ul class="clients-grid mb0 column4 clearfix">
      <li><%= link_to image_tag("maersk.jpg", :class => "img-logo", :alt => "Maersk"), "https://www.maersk.com/", :target => "_blank" %></li>
      <li><%= link_to image_tag("boskalis.jpg", :class => "img-logo", :alt => "Boskalis"), "http://boskalis.com/", :target => "_blank" %></li>
      <li><%= link_to image_tag("dbbw.jpg", :class => "img-logo", :alt => "Boskalis"), "https://www.debrauw.com/", :target => "_blank" %></li>
      <li><%= link_to image_tag("deloitte.jpg", :class => "img-logo", :alt => "Deloitte"), "https://www2.deloitte.com/global/en.html?icid=site_selector_global", :target => "_blank" %></li>

    </ul>
</div>

<div class="container pt90 pb50">
    <div class="title-heading1 mb60">
        <h3>O.N.G.</h3>
    </div>
    <ul class="clients-grid mb0 column4 clearfix">
      <li><%= link_to image_tag("wwf.png", :class => "img-logo", :alt => "WWF"), "http://www.worldwildlife.org/", :target => "_blank" %></li>
      <li><%= link_to image_tag("peeda-logo.png", :class => "img-logo", :alt => "Peeda"), "https://peeda.net/", :target => "_blank" %></li>
      <li><%= link_to image_tag("girls.png", :class => "img-logo", :alt => "Girls for change"), "http://www.girlsforachange.org/", :target => "_blank" %></li>
      <li><%= link_to image_tag("perc.png", :class => "img-logo", :alt => "Perc"), "https://perc.ca/", :target => "_blank" %></li>


    </ul>
</div>

<div class="container pt90 pb50">
    <div class="title-heading1 mb60">
        <h3>Partenaires Académiques</h3>
    </div>
    <ul class="clients-grid mb0 column4 clearfix">
      <li><%= link_to image_tag("queens.png", :class => "img-uni", :alt => "Université de Queens"), "https://www.queensu.ca/", :target => "_blank" %></li>
      <li><%= link_to image_tag("rennes.png", :class => "img-uni", :alt => "Université de Rennes1"), "https://www.univ-rennes1.fr/", :target => "_blank" %></li>
      <li><%= link_to image_tag("oxford.png", :class => "img-uni", :alt => "Université d'Oxford"), "http://www.ox.ac.uk/", :target => "_blank" %></li>
      <li><%= link_to image_tag("polynesie.png", :class => "img-uni", :alt => "UPF de Polynésie"), "http://www.upf.pf/fr", :target => "_blank" %></li>


    </ul>
</div>

<div class="container pt90 pb50">
    <div class="title-heading1 mb60">
        <h3>Entreprises</h3>
    </div>
    <ul class="clients-grid mb0 column4 clearfix">

      <li><%= link_to image_tag("latham.jpg", :class => "img-logo", :alt => "Latham"), "https://www.lw.com/AboutUs/ProBono", :target => "_blank" %></li>
      <li><%= link_to image_tag("microsoft_greyscale.jpg", :class => "img-logo", :alt => "Salesforce"), "https://www.salesforce.com/", :target => "_blank" %></li>
      <li><%= link_to image_tag("DeepGreen.jpg", :class => "img-logo", :alt => "Deep Green"), "https://deep.green/", :target => "_blank" %></li>
      <li><%= link_to image_tag("akzonobel.jpg", :class => "img-logo", :alt => "akzonobel"), "https://www.akzonobel.com/", :target => "_blank" %></li>


    </ul>
</div>

app/views/home/presentation.html.erb
<div class="page-custom-header title-space-lg bg-parallax mb80 parallax-overlay" data-jarallax='{"speed": 0.2}' style='background-image: url(<%=asset_path 'keyboard.jpg' %>);background-position:center;'>
            <div class="container">
                <div class="row">
                    <div class=" col-md-6">
                        <h2 class="text-white">Une communauté proactive</h2>

                        <p class="text-white-gray">
                        <strong>U-MAN</strong> est un projet visant à moderniser et simplifier l'échange d'information touchant la recherche sur les écosytèmes naturels.
                        </p>
                        <a href="/partenaires" class="btn btn-white-outline">Voir nos partenaires</a>
                    </div>
                </div>
            </div>
        </div><!--page title end-->

        <!-- Notre solution -->
        <!-- bouton en savoir plus vers technologie -->

        <!-- A propos de nous-->
        <!-- Partenaires  -->
        <!-- equipe -->
        <!-- Participer -->
        <!-- En savoir plus -->




                <div class='bg-white border-btm1'>
                    <div class='container pt80 pb90'>
                        <div class='row align-items-center'>
                            <div class='col-lg-8 mb70'>

                                <h3 class='title-font mb20'>Un objectif simple</h3>
                                    <p class='lead-p1'>
                                      Le projet U-MAN est né de la nécessité d'une compréhension des relations des organismes vivant entre eux et dans leurs environnements.</p class="lead-p1">
                                    <p class="lead-p1">Le secteur de la production agricole raisonnée et forestière ainsi que les biocarburants est en évolution rapide.</p class="lead-p1">
                                    <p class="lead-p1">Nous souhaitons faciliter cette conversion et aller encore plus loin. La permaculture s'inscrit dans cette démarche comme une solution innovante et évidente.<p class="lead-p1">U-MAN initie le premier mouvement de recherche et d'agrégation à visée internationale. Notre objectif le croisement de données et la recherche de résultat non linéaire.
                                  </p>
                              </div>
                                <div class='col-lg-4 ml-auto mb40 wow fadeInUp' data-wow-delay=".1s">
                                <img src=<%= asset_path 'coalmine.jpg' %> alt='' class='img-presentation'>
                            </div>
                        </div>
                    </div>
                </div><!--feature-->
                <div class='bg-white border-btm1'>
                    <div class='container pt90 pb50'>
                        <div class='row align-items-center'>
                            <div class='col-lg-2 mb40 wow fadeInUp' data-wow-delay='.2s'>
                                <img src=<%= asset_path 'computer.jpg' %> alt='' class='img-presentation'>
                            </div>
                        <div class='col-lg-9 mr-auto mb80'>

                                <h3 class='title-font mb20'>Une approche scientifique</h3>
                                <p class='lead-p1'>
                                  La connaissance humaine à progressé de manière exponentielle, en matière de biologie, de compréhension du microbiosme et d'étude du vivant.</p class="lead-p1">

                              <p class="lead-p1">Il est impératif de mettre en relation les données et études développées au niveau international entre elles.</p class="lead-p1">


                              <p class="lead-p1">Nous nous efforçons de simplifier l'agglomération de données dans le but de faire émerger des qualités dans le croisement de celle-ci.<br> Cella nous permet des découvertes, via le DEEP LEARNING, qui en d'autre temps aurais nécessité des générations d'agriculteurs attentifs et consciencieux.<br></p class="lead-p1">

                            <p class="lead-p1">Ainsi, le savoir le plus ancien de l'humanité, l'agriculture, et notre évolution propre dans notre écosystème en tant qu'espèce, se trouverait OPEN SOURCE au niveau international.</p class="lead-p1">

                            </div>

                        </div>
                    </div>
                </div><!--feature-->
                <div class='bg-white'>
                    <div class='container pt90 pb50'>
                        <div class='row align-items-center'>
                            <div class='col-lg-5 ml-auto mb40'>


                                <h3 class='title-font mb20'>Un engagement Humain</h3>
                                <p class='lead'>
                                  U-MAN, est une plateforme a destinations de professionels, pouvant accélérer son développement. L'objectif dès lors a été de créer un système participatif, permettant au personnes fortement impliquées de partager leur savoir.</p class="lead">

                              <p class="lead">Cet outil est appellé a évolué avec la volonté de la communauté et des capacités techniques a notre disposition.</p class="lead">


                              <p class="lead">La participation, d'acteurs exterieurs via des collaborations et des interventions au sein de U-MAN, nous permet d'accélérer notre croissance.</p class="lead">

                            <p class="lead">Notre volonté s'inscrit dans le cadre d'une reconstruction de nos écosystemes, et dans l'établissement d'une pensée nouvelle de l'agriculture, via une rentabilité retrouvée et prouvé de nos écosystèmes.</p class="lead">

                                </p>

                            </div>
                            <div class='col-lg-3 mr-auto mb40 wow zoomInUp' data-wow-delay=".1s">
                                <img src=<%= asset_path 'hand.jpg' %> alt="" class="img-presentation">
                            </div>
                        </div>
                    </div>
                </div>